server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parameta_db
    username: root
    password: P4R4M3T421
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
        ddl-auto: update